### ISSUE TITLE
New section on "top 10 things we didn't cover"

### ISSUE THREAD

**Issue by stephenpcook** [UniExeterRSE/intro-unix-shell#12]
I'm thinking of an extra section for in the wrap-up, listing things in unix/bash that we didn't cover, maybe with some links for further reading.

1. Path : `~/bin/`
2. Hidden files : `touch .hidden && ls && ls -a`
3. `.bashrc`, `.bash_profile`
4. {} wild-card : `touch file-{001..100}`
5. Return codes : `ks && echo "done?"`
6. stdin/stderr and redirection : `ks 2>&1 | cat`
7. Job control : `&`, `ps`, `fg`, `bg`, `kill`
8. Environment variables : `export`
9. Intro to unix filesystem
10. emacs and vim : `vimtutor`

Candidates not making the cut
- "Magic" variables : `mkdir tmp_dir && cd $_`
- extra bash scripting (if/else, while, case)
- Line endings and ascii : `\n\r`
- calculations : `echo $((10**2 - 1))`

Maybe it could be curated down to "10 things we didn't cover" and  could have ~1 minute each?

(Following discussion with @simonkirbysimonkirby)

**Comment by simonkirbysimonkirby** [comment]
Happy for you to curate down to 10 items. We can write a few sentences and provide a link to a resource for further reading for each.

**Comment by stephenpcook** [comment]
Moved over to coding-for-reproducible-research/CfRR_Courses#110
